version: "3.3"  # optional since v1.27.0
services:
  app:
    build: .
    volumes:
      - /sys:/sys
#  influxdb:
#    image: influxdb:2.3.0
#    ports:
#      - "8086:8086"
#    environment:
#      - DOCKER_INFLUXDB_INIT_MODE=setup
#      - DOCKER_INFLUXDB_INIT_USERNAME=root
#      - DOCKER_INFLUXDB_INIT_PASSWORD=password
#      - DOCKER_INFLUXDB_INIT_ORG=demax
#      - DOCKER_INFLUXDB_INIT_BUCKET=temperature
#    volumes:
#      - influxdb2:/var/lib/influxdb2
#  grafana:
#    image: grafana/grafana:8.2.6
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./resources/configs/datasrc.yml:/etc/grafana/provisioning/datasources/influx-datasrc.yml:ro
#      - ./dashboards:/var/lib/grafana/dashboards
#      - ./resources/configs/dashboard-provider.yml:/etc/grafana/provisioning/dashboards/dashboard-provider.yml:ro
#      - ./resources/configs/grafana.ini:/etc/grafana/grafana.ini:ro
volumes:
  influxdb2:

